apiVersion: v1
kind: Pod
metadata:
  name: testapp
  namespace: testapp
spec:
  containers:
  - name: testapp
    image: testapp:latest
    imagePullPolicy: Never
    resources:
      limits:
        memory: "200Mi"
