apiVersion: v1
kind: Pod
metadata:
  name: testapp
  namespace: testapp
spec:
  containers:
  - name: testapp
    image: rapidfort/flaskapp
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "200Mi"
